version: "2"
services:
  mongoR-1:
    container_name: mongoR-1
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /data/db1:/data/db
  mongoR-2:
    container_name: mongoR-2
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /data/db2:/data/db
  mongoR-3:
    container_name: mongoR-3
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    environment:
      TERM: xterm
    volumes:
      - /data/db3:/data/db
  mongoC-1:
    container_name: mongoC-1
    image: mongo
    command: mongod --configsvr --replSet cfg1 --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /data/config1:/data/db
  mongoC-2:
    container_name: mongoConfig-2
    image: mongo
    command: mongod --configsvr --replSet cfg1 --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /data/config2:/data/db
  mongoC-3:
    container_name: mongoConfig-3
    image: mongo
    command: mongod --configsvr --replSet cfg1 --dbpath /data/db --port 27017
    environment:
      TERM: xterm
    expose:
      - "27017"
    volumes:
      - /data/config3:/data/db
  mongoS-1:
    container_name: mongoS1
    image: mongo
    depends_on:
      - mongoConfig-1
      - mongoConfig-2
    command: mongos --configdb cfg1/mongoC-1:27017,mongoConfig-2:27017,mongoConfig-3:27017 --port 27017
    ports:
      - 27019:27017
    expose:
      - "27017"
    volumes:
      - /data/seed:/data/seed
  mongoS-2:
    container_name: mongoS2
    image: mongo
    depends_on:
      - mongoConfig-1
      - mongoConfig-2
    command: mongos --configdb cfg1/cfg1-1:27017,cfg1-2:27017,cfg1-3:27017 --port 27017
    ports:
      - 27020:27017
    expose:
      - "27017"



