version: "2"
services:
  mongoRep-1a:
    container_name: mongoRep-1a
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /data/rep1a:/data/db
  mongoRep-1b:
    container_name: mongoRep-1b
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27027:27017
    expose:
      - "27017"
    volumes:
      - /data/rep1b:/data/db
  mongoRep-1c:
    container_name: mongoRep-1c
    image: mongo
    command: mongod --shardsvr --replSet rs1 --dbpath /data/db --port 27017
    ports:
      - 27037:27017
    expose:
      - "27017"
    volumes:
      - /data/rep1c:/data/db