version: "2"
services:
  module:
    build: .
    expose:
      - "3000"
    restart: always
  mongoS:
    depends_on:
      - module
    image: mongo
    container_name: mongoS
    expose:
      - "27017"
    volumes:
      - "./mongos/setup.sh"
    command:
      - setup.sh
    restart: always
