version: "2"
services:
  mongoR-2a:
    container_name: mongoR-2a
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /data/rep2a:/data/db
  mongoR-2b:
    container_name: mongoR-2b
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /data/rep2b:/data/db
  mongoR-2c:
    container_name: mongoR-2c
    image: mongo
    command: mongod --shardsvr --replSet rs2 --dbpath /data/db --port 27017 --bind_ip 0.0.0.0
    ports:
      - 27017:27017
    expose:
      - "27017"
    volumes:
      - /data/rep2c:/data/db

rs.initiate({ _id: "rs2", members: [ { _id: 0, host: "172.31.7.223:27017" }, { _id: 1, host: "172.31.7.223:27027" }, { _id: 2, host: "172.31.7.223:27037" } ]})


rs.initiate({ _id: "rs2", members: [ { _id: 0, host: "172.31.8.68:27017" }, { _id: 1, host: "172.31.12.251:27017" }, { _id: 2, host: "172.31.7.181:27017" } ]})